[features]
seeds = false
[programs.devnet]
gifportal = "3gyBddu56VrbYSncpFQHUGd7155e2HjWcdqf5bfkxHcS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kylereynolds/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"